<?php
include "conexion.php";
	
	
$consulta2= 'insert into ("nombre") profesores values
("Cynthia Leticia Acosta Almodovar"),
("Jose Eduardo Acosta Cano de los Rios"),
("Pedro Rafael Acosta Cano de los Rios"),
("Raul Arturo Acosta Chavez"),
("Benito Aguirre Saenz"),
("Adda Olivia Alanis Araiza"),
("Gerardo Alcantar Burrola"),
("Arturo Alejo Tepate"),
("Manuel Altes Cardenas"),
("Cornelio Alvarez Herrera"),
("Vania Carolina Alvarez Olivas"),
("Rocio Alvidrez Rodriguez"),
("Ramon Anchondo Perez"),
("Maria Antonia Aragon De los Rios"),
("Juan Fernando Arevalo Ruiz"),
("Jorge Alberto Arias Mendoza"),
("Mirna Teresita Armendariz Hernandez"),
("Efren Armendariz Mota"),
("Alejandra Arredondo Mora"),
("Angel Claudio Arzola Mazuca"),
("Fernando Rafael Astorga Bustillos"),
("Gabriela Leticia Avila Orozco"),
("Yolanda Avitia Rodriguez"),
("Vanessa Baeza Olivas"),
("Wilibaldo Barrada Morales"),
("Claudia Barraza Bolivar"),
("Francisco Barraza Jimenez"),
("Miguel Antonio Barreada Contreras"),
("Alfonso Jose Barroso Barajas"),
("Alma Denisse Batista Galvan"),
("Alonso Bautista Villalobos"),
("Oscar Beltran Gomez"),
("Eduardo Enrique Benitez Read"),
("Ricardo Blanco Vega"),
("Karla Bojorquez Gutierrez"),
("Oscar Mauricio Borunda Carrasco"),
("Martha Cecilia Breceda Vargas"),
("Diana Lorelei Bueno Valles"),
("Elizabeth Burrola Marquez"),
("Rosalba Bustillos Villagran"),
("Raymundo Caballero Flores"),
("Marisela Ivette Caldera Franco"),
("Martha Lorena Calderon Fernandez"),
("Alejandro Calderon Landaverde"),
("Alberto Camacho Rios"),
("Victor Luis Camara Aranda"),
("Luis Alfonso Campos Hermosillo"),
("Oscar Cardenas Morales"),
("Claudio Hiram Carmona Jurado"),
("Rene Fernando Carrasco Hernandez"),
("Raul Carrera Resendez"),
("Michelle Carrete Evangelista"),
("Daniela Alejandra Carrillo Treviño"),
("Jose Lino Carrillo Villalobos"),
("Abelardo Casas Comaduran"),
("Jose Castañeda Avila"),
("Rocio Guadalupe Castro Lozoya"),
("Romualdo Chanes Mendoza"),
("Jose Alberto Chaparro Tarango"),
("Jacobo Chavez Gonzalez"),
("Aldo Antonio Cisneros Rodriguez"),
("Manuel Contreras Caraveo"),
("Perla Ivonne Cordero De los Rios"),
("Luis Alberto Corona Reyes"),
("Paola Corona Villa"),
("Mariano Corral Banda"),
("Pedro Enrique Cossio Rodriguez"),
("Mario Andres Cuevas Gutierrez"),
("Rodrigo De la Garza Aguilar"),
("Marco Polo De Leon Palma"),
("Jose Saul De Lira Miramontes"),
("Maria Teresa Delgado Caballero"),
("Afren Armando Delgado Enrique"),
("Guillermo Javier Diaz Greene"),
("Ricardo Zeferino Diaz Morales"),
("Guillermo Diaz Murillo"),
("Raul Reveriano Diaz Quezada"),
("Jesus Miguel Dominguez Dominguez"),
("Alberto Dominguez Quintana"),
("Luis Alonso Dominguez Ramos"),
("Victor Alonso Dominguez Rios"),
("Evaristo Duran Magos"),
("Candy Aurora Duran Ornelas"),
("Luis Gerardo Durstewitz Marta"),
("Alberto Enriquez Bailon"),
("Dalila Jacqueline Escudero Almanza"),
("Jesus Mario Espadas Roque"),
("Alma Rosa Esparza Chavez"),
("Rebeca Minerva Espara Machuca"),
("Nietle Comuna de Paris Esparza Vazquez"),
("Hector Trinidad Espejel Fernandez"),
("Daphne Espejel Garcia"),
("Vanessa Veronica Espejel Garcia"),
("Maria Socorro Espino Valdes"),
("Jose Roberto Espinoza Prieto"),
("Maria Elena Estevane Ortega"),
("Irma Graci Estrada Gutierrez"),
("Juan Carlos Fernandez Chavez"),
("Flores Rogelio Fernandez De Lara"),
("Claudia Annette Fernandez Perez"),
("Luis Carlos Flores Camacho"),
("Juan Pablo Flores De los Rios"),
("Elizabeth Flores Hernandez"),
("Oscar Florez Mendez"),
("Adriana Flores Salcido"),
("Gaston Rene Fourzan Fierro"),
("Miguel Franco Rubio"),
("David Alberto Frescas Chong"),
("Miguel Angel Galaviz Zamarron"),
("Carlos Alfonso Gameros Morales"),
("Margarita Garcia Rivas"),
("Carlos Eduardo Garcia Vargas"),
("Eber Ezequiel Gardea Solis"),
("Hector Alejandro Gomez Corral"),
("Juan Eli Gomez Vidal"),
("Javier Gonzalez Cantu"),
("Luis Carlos Gonzalez Gurrola"),
("Miguel Angel Gonzalez Nuñez"),
("Cesar Gonzalez Valenzuela"),
("Natalia Karina Gonzalez Valenzuela"),
("Jorge Gramer Rivera"),
("Ernesto Guerrero Lestarjette"),
("Blanca Patricia Guerrero Martinez"),
("Addai Guerrero Quiñones"),
("Amalia Irene Guerrero Rodriguez"),
("Carmen Elena Gutierrez Sandoval"),
("Arnoldo Guzman Nieves"),
("Andrei Helo Guereca"),
("Marcela Hernandez Acosta"),
("Elva Socorro Hernandez Hernandez"),
("Hector Hugo Hernandez Hernandez"),
("Gilberto Hernandez Juarez"),
("Alfonso Hernandez Lopez"),
("Fabian Vinicio Hernandez Martinez"),
("Gerardo Arturo Hernandez Talamantes"),
("Jose Luis Herrera Aguilar"),
("Jorge Herrera Gallardo"),
("Eduardo Florencio Herrera Peraza"),
("Nalleli Herrera Pineda"),
("Omar Hinojos Carrasco"),
("Octavio Raul Hinojosa De la Garza"),
("Rafael Holguin Rivas"),
("Rafael Holguin Rivas"),
("Nicolas Holguin Rodriguez"),
("Karina Edith Jimenez Lozano"),
("Raul Alfredo Jimenez Lozano"),
("Mario Alberto Juarez Macias"),
("Karla Ivonne Juarez Magallanes"),
("Arion Ehecatl Juarez Menchaca"),
("Sergio Jurado Medina"),
("Jose Luis Landeros Rivas"),
("Federico Landeros Rodriguez"),
("Ivan Enrique Lara Gonzalez"),
("Carlos Hugo Larrinua Pacheco"),
("Carlos Ignacio Leyva Delgado"),
("Sandra Gabriela Leyva Delgado"),
("Leonardo Agustin Llamas Jimenez"),
("Geronimo Llerar Meza"),
("Hernan Ricardo Lopez De la Riva"),
("Victor Hugo Lopez De Lara Chavez"),
("Marcela Esenia Lopez Ochoa"),
("Claudia Lorena Lopez Olivas"),
("Miguel Angel Lopez Santillan"),
("Aracely Lopez Terrazas"),
("Jesus Humberto Loya Mercado"),
("Roberto Carlos Luna Lozoya"),
("Mario Alberto Madrid Perez"),
("Gregorio Arturo Madrid Ramirez"),
("Fabricio Alan Madrigal Vazquez"),
("Ricardo Majalca Martinez"),
("Magdalena Maldonado Valenzuela"),
("David Maloof Flores"),
("Adolfo Marquez Acosta"),
("Juan Armando Marquez Enriquez"),
("Eloy Normando Marquez Gonzalez"),
("Pedro Rafael Marquez Gutierrez"),
("Leonel Marquez Saenz"),
("Matias Marquez Saenz"),
("Nicolas - Martinez"),
("Cesar Martinez Acosta"),
("Reynaldo Martinez Armenta"),
("Miguel Angel Martinez Lopez"),
("Fernando Martinez Reyes"),
("Javier Maclen Martinez Rodriguez"),
("Javier Alejandro Martinez Rubio"),
("Kristian Martinez Sagredo"),
("Jose Alejandro Martinez Sosa"),
("David Eduardo Medina Guzman"),
("Tanya Lizeth Medina Ronquillo"),
("Luis German Mejia Borja Mendez"),
("Jose Leonel Melchor Ceballos"),
("Pedro Angel Mendez Alvarado"),
("Jorge Mendoza Hernandez"),
("Edgar Eduardo Mendoza Velazquez"),
("Dulce Carolina Minor Avila"),
("Hector Minor Velazquez"),
("Enrique Miranda Flores"),
("Hugo Molina Martinez"),
("Oscar Humberto Monjaras Enriquez"),
("Michel Yadira Montelongo Flores"),
("Jose Carlos Montero De Anda"),
("Luis Carlos Montero Leon"),
("Jose Mora Ruacho"),
("Luis Enrique Morales Gutierrez"),
("Hermes Moreno Alvarez"),
("Alicia Sagrario Moreno Arvizo"),
("Olga Teresa Moriel Acosta"),
("Luis Hebbel Moriel Maldonado"),
("Manuel Antolin Morita Ugarte"),
("Pedro Alberto Muela Molina"),
("Eric Alejandro Muller Garcia"),
("Alejandro Muro Hernandez"),
("Gabriela Muñiz Chavez"),
("Ana Yahaira Muños Gamboa"),
("Jesus Manuel Muñoz Languero"),
("Marisa Isabel Muñoz Ochoa"),
("Claudia Georgina Nava Dino"),
("Carmen Julia Navarro Gomez"),
("Erik Alberto Ochoa Corona"),
("Alan Orlando Ochoa Renteria"),
("Jorge Enrique Ochoa Torres"),
("Marcos Gabriel Ogaz Gonzalez"),
("Cecilia Olivia Olague Caballero"),
("Rosa Imelda Olague Caballero"),
("Hugo Alfredo Olivas Acosta"),
("Alejandra Olivas Davila"),
("Olga Cecilia Olivas Rivera"),
("Mario Alberto Olmos Marquez"),
("Alberto Ornelas Hernandez"),
("Alfredo Ornelas Hernandez"),
("Alicia Ornelas Vargas"),
("Adrian Isaac Orpinel Ureta"),
("Patricia Guadalupe Orpinel Ureta"),
("Ricardo Ortega Diaz"),
("Hermila Ortega Mendoza"),
("Linda Carolina Ortega Robles"),
("Eduardo Ortiz Natividad"),
("Abundio Osuna Vizcarra"),
("Angelica Oviedo Garcia"),
("Rafael Edipo Palma Castillo"),
("Pamela Sisi Paredes Araiza"),
("Sergio Arturo Payan Gomez"),
("Velia Perez Gonzalez"),
("Oscar Daniel Perez Piñon"),
("Gerardo Perez Reveles"),
("Miriam Zulemy Perez Rodallegas"),
("Adan Pinales Munguia"),
("Jesus Roberto Pizarro Chavez"),
("Irma Liz Piñon Carmona"),
("Refugio Antonio Piñon Carmona"),
("Nahim Josafat Ponce Lucero"),
("Jose Antonio Portillo Oceguera"),
("Yessica Prieto Maldonado"),
("Olanda Prieto Ordaz"),
("Alberto Quintana Dominguez"),
("Cristina Idalia Quintana Silveira"),
("Erick Octavio Quiones Rodriguez"),
("Luis Carlos Quiñones Baca"),
("Edna Guadalupe Radovich Perez"),
("Francisco Ramirez Kohler"),
("Rocio Alejandra Ramirez Lira"),
("Luis Antonio Ramirez Martinez"),
("Gabriela Rascon Soto"),
("Julia Liliana Requeña Yañez"),
("Ignacio Alfonso Reyes Cortes"),
("Carmen Rosalia Reyes Reyna"),
("Manuel de Jesus Rincon Camacho"),
("Abril Cecilia Rios Lopez"),
("Aurora Robledo Ruiz"),
("Valentin Federico Rodriguez Alvarado"),
("Ricardo Alberto Rodriguez Fonseca"),
("Amparo Margarita Rodriguez Gallegos"),
("Carlos Fransisco Rodriguez Guevara"),
("Beatriz Adriana Rodriguez Varela"),
("Hector David Romero Granados"),
("Jorge Armando Rubio Perea"),
("Adriana Ruiz Anchondo"),
("Hector David Ruiz Cisneros"),
("Yesica Olivia Ruiz Holguin"),
("Jorge Iden Ruiz Quintana"),
("Maria Selene Ruiz Rivero"),
("Rodrigo Ruiz Santos"),
("Oscar Ramses Ruiz Varela"),
("Alfonso Saens Marquez"),
("Jesus Saenz Olivas"),
("Victor Alfonso Salas Aguilar"),
("Lizbeth Salas Lechuga"),
("Luis Alfonso Salcido Hernandez"),
("Saul Alejandro Salomon Jaramillo"),
("Hugo Alejandro San Martin Benavides"),
("Marco Antonio Sanchez Vazquez"),
("Raul Sandoval Jabalera"),
("Laura Veronica Sandoval Romero"),
("Ivonne Aracely Santillan Martinez"),
("Jose Santos Garcia"),
("Daniel Sayto Corona"),
("David Armando Sias Casas"),
("Leonardo Sias Elizondo"),
("Humberto Silva Hidalgo"),
("Claudia Maria Sinaloa Rodriguez"),
("Sergio Solis Castillo"),
("Gilberto Sosa Najera"),
("Erick Ivan Teran Corral"),
("Carlos Alberto Terrazs Venegas"),
("Agustin Javier Tonche Ramos"),
("Daniel Oviel Torres Cisneros"),
("Aaron Torres Orozco"),
("Joaquin Gilberto Treviño Davila"),
("Edgar Trujillo Preciado"),
("Gerardo Trujillo Schiaffino"),
("Maria Ugarte De la Rosa"),
("Wenceslado Melecio Urbina Chavez"),
("Adolfo Valdes Chavez"),
("Carlos Valdez Fragoso"),
("Julio Cesar Valdez Muñoz"),
("Erick Saul Varela Hernandez"),
("Beatriz Vazquez Gonzalez"),
("Maria Isabel Vazquez Gonzalez"),
("Mayra Elena Vega Carrasco"),
("LizzetVelazquez Vega Portillo"),
("Maria Alejandra Velazquez Cazares"),
("Roberto Velazquez Talamantes"),
("Jose Elias Villa Herrera"),
("Marisol Villa Herrera"),
("Maria de Lourdes - Villalba"),
("Alejandro Villalobos Aragon");';
$regresa2 = mysqli_query($conexion,$consulta2);
?>